### ISSUE TITLE
Standalone tests

### ISSUE THREAD

**Issue by hanjukim** [terra-project/fcd#2]
Change tests so they can run on an empty db (for example by running migrations and injecting mocked data if not present).
Maybe see if possible to mock lcd calls too (less problematic than db calls for ci runs)

I will help CI or external contributors running tests without relying on existing infrastructure.

**Comment by hanjukim** [comment]
blocks #3

**Comment by etienne-napoleone** [comment]
Given development is shifting to mantle, it might not be necessary to invest time on this
